Repository hecrj/coffee, pull requests merged in 2019-08, with the labels that each got.

#79 Add `Game::is_finished` and support graceful quits
  src/game.rs
  src/ui.rs
Labels: feature

#60 Update `wgpu` backend to latest API
  Cargo.toml
  src/graphics/backend_wgpu/font.rs
  src/graphics/backend_wgpu/mod.rs
  src/graphics/backend_wgpu/quad.rs
  src/graphics/backend_wgpu/surface.rs
  src/graphics/backend_wgpu/texture.rs
  src/graphics/backend_wgpu/triangle.rs
Labels: improvement

#81 Fix validation error on `wgpu` triangle pipeline
  CHANGELOG.md
  Cargo.toml
  src/graphics/backend_wgpu/triangle.rs
  tests/_graphics/models/mesh.png
Labels: bug

#83 Implement a `ProgressBar` widget
  .gitignore
  examples/progress.rs
  src/ui.rs
  src/ui/renderer.rs
  src/ui/renderer/progress_bar.rs
  src/ui/widget.rs
  src/ui/widget/progress_bar.rs
Labels: feature

#84 Implement an `Image` widget
  examples/image.rs
  src/graphics/rectangle.rs
  src/ui.rs
  src/ui/renderer.rs
  src/ui/renderer/image.rs
  src/ui/widget.rs
  src/ui/widget/image.rs
Labels: feature

#82 Migrate to GitHub CI
  .github/workflows/integration.yml
  .travis.yml
  tests/diff_shaders
Labels: improvement
