Repository hecrj/coffee, pull requests merged in 2019-06, with the labels that each got.

#41 Deny `rust_2018_idioms`
  src/debug/basic.rs
  src/debug/null.rs
  src/game.rs
  src/graphics/backend_gfx/font.rs
  src/graphics/backend_gfx/pipeline.rs
  src/graphics/backend_wgpu/font.rs
  src/graphics/backend_wgpu/texture.rs
  src/graphics/batch.rs
  src/graphics/canvas.rs
  src/graphics/font.rs
  src/graphics/image.rs
  src/graphics/target.rs
  src/graphics/texture_array.rs
  src/graphics/texture_array/batch.rs
  src/graphics/window/frame.rs
  src/graphics/window/mod.rs
  src/lib.rs
  src/load.rs
  src/load/loading_screen.rs
  src/load/loading_screen/progress_bar.rs
  src/result.rs
  src/ui.rs
  src/ui/core/element.rs
  src/ui/core/interface.rs
  src/ui/core/renderer.rs
  src/ui/core/widget.rs
  src/ui/renderer.rs
  src/ui/widget/button.rs
  src/ui/widget/checkbox.rs
  src/ui/widget/column.rs
  src/ui/widget/radio.rs
  src/ui/widget/row.rs
  src/ui/widget/slider.rs
  src/ui/widget/text.rs
Labels: improvement

#50 Mesh support
  CHANGELOG.md
  Cargo.toml
  examples/mesh.rs
  src/graphics/backend_gfx/mod.rs
  src/graphics/backend_gfx/quad.rs
  src/graphics/backend_gfx/shader/quad.frag
  src/graphics/backend_gfx/shader/quad.vert
  src/graphics/backend_gfx/shader/triangle.frag
  src/graphics/backend_gfx/shader/triangle.vert
  src/graphics/backend_gfx/triangle.rs
  src/graphics/backend_wgpu/mod.rs
  src/graphics/backend_wgpu/quad.rs
  src/graphics/backend_wgpu/shader/quad.frag
  src/graphics/backend_wgpu/shader/quad.frag.spv
  src/graphics/backend_wgpu/shader/quad.vert
  src/graphics/backend_wgpu/shader/quad.vert.spv
  src/graphics/backend_wgpu/shader/triangle.frag
  src/graphics/backend_wgpu/shader/triangle.frag.spv
  src/graphics/backend_wgpu/shader/triangle.vert
  src/graphics/backend_wgpu/shader/triangle.vert.spv
  src/graphics/backend_wgpu/texture.rs
  src/graphics/backend_wgpu/triangle.rs
  src/graphics/batch.rs
  src/graphics/canvas.rs
  src/graphics/image.rs
  src/graphics/mesh.rs
  src/graphics/mod.rs
  src/graphics/shape.rs
  src/graphics/target.rs
  src/graphics/texture_array/batch.rs
Labels: feature

#51 Fix `Font::measure` and `Text` widget
  src/graphics/backend_gfx/font.rs
  src/graphics/backend_wgpu/font.rs
  src/graphics/font.rs
  src/ui/renderer/text.rs
Labels: bug

#29 Controller events
  .travis.yml
  CHANGELOG.md
  Cargo.toml
  README.md
  examples/gamepad.rs
  examples/input.rs
  examples/mesh.rs
  examples/particles.rs
  src/game.rs
  src/graphics/window/event.rs
  src/input.rs
  src/input/event.rs
  src/input/gamepad.rs
  src/input/gamepad/event.rs
  src/input/keyboard.rs
  src/input/keyboard/event.rs
  src/input/keyboard_and_mouse.rs
  src/input/mouse.rs
  src/input/mouse/button.rs
  src/input/mouse/event.rs
  src/input/window.rs
  src/input/window/event.rs
  src/ui.rs
  src/ui/core/event.rs
  src/ui/widget/button.rs
  src/ui/widget/checkbox.rs
  src/ui/widget/radio.rs
  src/ui/widget/slider.rs
Labels: feature

#52 Implement `Element::explain`
  src/graphics/mesh.rs
  src/ui/core/element.rs
  src/ui/core/renderer.rs
  src/ui/renderer.rs
Labels: feature

#53 Remove `position` argument from `Batch::draw`
  CHANGELOG.md
  examples/particles.rs
  src/graphics/batch.rs
  src/graphics/texture_array/batch.rs
  src/ui/renderer.rs
Labels: improvement

#55 Rename `Font::load` to `Font::load_from_bytes`
  CHANGELOG.md
  examples/color.rs
  examples/input.rs
  src/graphics/font.rs
  src/ui/renderer.rs
Labels: improvement

#56 0.3.0
  CHANGELOG.md
  Cargo.toml
  README.md
  examples/README.md
  examples/counter.rs
  examples/gamepad.rs
  examples/mesh.rs
  examples/particles.rs
  examples/ui.rs
  images/examples/particles.png
  src/debug.rs
  src/debug/basic.rs
  src/game.rs
  src/graphics.rs
  src/graphics/backend_gfx/mod.rs
  src/graphics/batch.rs
  src/graphics/canvas.rs
  src/graphics/color.rs
  src/graphics/image.rs
  src/graphics/mesh.rs
  src/graphics/quad.rs
  src/graphics/shape.rs
  src/graphics/target.rs
  src/graphics/texture_array/batch.rs
  src/graphics/texture_array/builder.rs
  src/graphics/texture_array/loader.rs
  src/graphics/transformation.rs
  src/graphics/window.rs
  src/lib.rs
  src/load.rs
  src/load/loading_screen.rs
  src/load/task.rs
  src/ui.rs
Labels: feature, improvement
