Repository hecrj/coffee, pull requests merged in 2019-05, with the labels that each got.

#26 Show time spent in `Debug::draw` in debug view
  src/debug/basic.rs
  src/debug/null.rs
  src/lib.rs
Labels: improvement

#25 Make `Font::draw` support a `Target` instead of a `Frame`
  Cargo.toml
  examples/color.rs
  examples/input.rs
  examples/particles.rs
  src/debug/basic.rs
  src/graphics/backend_gfx/font.rs
  src/graphics/backend_gfx/mod.rs
  src/graphics/backend_gfx/surface.rs
  src/graphics/backend_gfx/types.rs
  src/graphics/backend_wgpu/font.rs
  src/graphics/backend_wgpu/mod.rs
  src/graphics/backend_wgpu/surface.rs
  src/graphics/backend_wgpu/types.rs
  src/graphics/font.rs
  src/graphics/target.rs
  src/graphics/text.rs
  src/graphics/window/frame.rs
  src/load/loading_screen.rs
Labels: feature

#33 Fullscreen support
  examples/color.rs
  examples/input.rs
  examples/particles.rs
  src/graphics/mod.rs
  src/graphics/transformation.rs
  src/graphics/window/frame.rs
  src/graphics/window/mod.rs
  src/graphics/window/settings.rs
  src/lib.rs
  src/load/loading_screen.rs
Labels: feature

#34 `Canvas::draw` is now generic
  src/graphics/canvas.rs
Labels: feature

#36 [WIP] Test SPIR-V differences on CI
  .travis.yml
  spirvtest
Labels: improvement

#37 Implement `Extend` and `ParallelExtend` for `Batch`
  CHANGELOG.md
  Cargo.toml
  examples/particles.rs
  src/graphics/batch.rs
Labels: feature, improvement
